[package]
name = "makerpi_rp2040"
version = "0.1.0"
authors = ["9names"]
edition = "2018"
homepage = "https://github.com/9names/makerpi-rp2040-rs"
description = "Board Support Package for the Cytron Maker Pi RP2040"
license = "bsd0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.2"
# rp2040-hal = { path = "../../rp2040-hal", version = "0.3.0"}
rp2040-hal = { git = "https://github.com/rp-rs/rp-hal", branch = "main"}
cortex-m-rt = { version = "0.7", optional = true }
embedded-time = "0.12.0"
usb-device= "0.2.8"
usbd-serial = "0.1.1"
usbd-hid = "0.5.1"

[dev-dependencies]
panic-halt= "0.2.0"
embedded-hal ="0.2.5"
cortex-m-rtic = "0.6.0-alpha.5"
# rp2040-boot2 = "0.1.2"
rp2040-boot2 = { git = "https://github.com/rp-rs/rp2040-boot2-rs", branch = "main" }
smart-leds = "0.3.0"
pio = { git = "https://github.com/rp-rs/pio-rs.git", branch = "main" }
ws2812-pio = { git = "https://github.com/ithinuel/ws2812-pio-rs" }
nb = "1.0"
# itertools = {version="0.10.1", no_default_features=true}

[features]
default = ["rt"]
rt = ["cortex-m-rt","rp2040-hal/rt"]
